apiVersion: apigatewayv2.services.k8s.aws/v1alpha1
kind: Stage
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: "animals-stage"
spec:
  apiRef:
    from:
      name: "{{ .Realease.Name }}-animals-api"
  stageName: "prod"
  autoDeploy: true
  description: "auto deployed stage for {{ .Release.Name }}-animals-api"
