apiVersion: apigatewayv2.services.k8s.aws/v1alpha1
kind: Integration
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/hook: PostSync
  name: "{{ .Release.Name }}-animals-integration"
spec:
  apiRef:
    from:
      name: "{{ .Release.Name }}-animals-api"
  integrationType: HTTP_PROXY
  integrationMethod: GET
  payloadFormatVersion: "1.0"
