apiVersion: apigatewayv2.services.k8s.aws/v1alpha1
kind: Integration
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/hook: PostSync
  name: "{{ .Release.Name }}-animals-integration"
  labels:
    {{- $relname := .Release.Name -}}
    {{ range $index, $service := (lookup "v1" "Service" $relname "").items }}
    {{ $service.metadata.name }} : "{{ $index }}"
    {{ end }}
spec:
  apiRef:
    from:
      name: "{{ .Release.Name }}-animals-api"
  integrationType: HTTP_PROXY
  integrationURI: {{ (index (lookup "v1" "Service" $relname "animals-api").status.loadBalancer.ingress 0).hostname}}
  integrationMethod: GET
  payloadFormatVersion: "1.0"
