apiVersion: apigatewayv2.services.k8s.aws/v1alpha1
kind: Route
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: "animals-route"
spec:
  apiRef:
    from:
      name: "animals-api"
  routeKey: "ANY /"
  targetRef:
    from:
      name: "animals-backend"
