apiVersion: v1
data:
  application.properties: |
    # server.port = 8888

    spring.datasource.url=jdbc:postgresql://postgresql:5432/{{ .Values.db.dbName }}
    spring.datasource.username={{ .Values.db.dbUser }}
    spring.datasource.password={{ .Values.db.dbUser }}
    spring.jpa.show-sql=true

    ## Hibernate Properties
    # The SQL dialect makes Hibernate generate better SQL for the chosen database
    spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

    # Hibernate ddl auto (create, create-drop, validate, update)
    spring.jpa.hibernate.ddl-auto = create-drop

    management.endpoints.web.exposure.include=health,info,prometheus
kind: ConfigMap
metadata:
  name: animals-api
