apiVersion: v1
kind: Endpoints
metadata:
  # the name here should match the name of the Service
  name: postgres
subsets:
  - addresses:
      - ip: {{ .Values.db.ip }}
    ports:
      - port: {{ .Values.db.port }}
