apiVersion: v1
kind: Service
metadata:
  annotations:
#    service.beta.kubernetes.io/aws-load-balancer-type: "alb"
#    service.beta.kubernetes.io/aws-load-balancer-type: "nlb-ip"
#    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-name: {{ .Release.Name }}
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-type: external
  labels:
    app: vaccines-api
  name: vaccines-api
spec:
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: vaccines-api
  sessionAffinity: None
  type: {{ .Values.service.type }}
