{{ if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
{{- if .Values.ingress.tls.enabled }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.ingress.tls.issuer }}
{{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
{{- if .Values.ingress.tls.enabled }}
  tls:
  - hosts:
    - {{ .Chart.Name }}.{{ .Values.ingress.baseDomain }}
    secretName: {{ .Chart.Name }}-tls
{{- end }}
  rules:
  - host: {{ .Chart.Name }}.{{ .Values.ingress.baseDomain }}
    http:
      paths:
      - backend:
          service:
            name: {{ .Chart.Name }}
            port:
              number: 8080
        path: /
        pathType: Prefix
{{ end }}
