{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name  }}-sa
  labels:
    {{- include "tenant-api.labels" . | nindent 4 }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::864674129776:role/EKSDynamoDBRole
{{- end }}
