apiVersion: apps/v1
kind: Deployment
metadata:
  name: landing-page
  labels:
    app: landing-page
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: landing-page
  template:
    metadata:
      labels:
        app: landing-page
    spec:
      containers:
      - name: landing-page
        image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 8080
        volumeMounts:
        - name: props-vol
          mountPath: /opt/app-root/src/.env
          subPath: .env
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      volumes:
        - name: props-vol
          configMap:
            name: landing-page
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - landing-page
            topologyKey: "kubernetes.io/hostname"
