apiVersion: v1
data:
  colorpad.conf: "location /confirm/orange {\n\t        proxy_http_version 1.1;\n\tproxy_pass http://orange:8080/confirm;\n}\n\nlocation /confirm/green {\n        proxy_http_version 1.1;  \n\n\tproxy_pass http://green:8080/confirm;\n}\n\nlocation /confirm/red {\n\t        proxy_http_version 1.1;  \n\n\tproxy_pass http://red:8080/confirm;\n}\n\nlocation /confirm/blue {\n        proxy_http_version 1.1;  \n\n        proxy_pass http://blue:8080/confirm;\n}\n\nlocation /confirm/purple {\n        proxy_http_version 1.1;  \n\tproxy_pass http://purple:8080/confirm;\n}\n\n"
kind: ConfigMap
metadata:
  name: colors-routes
