kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{.Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
  annotations:
    openshift.io/host.generated: 'true'
spec:
  to:
    kind: Service
    name: {{ .Chart.Name  }}
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None
