apiVersion: v1
data:
  pets-landing.conf: "location /tenant/ {\n\t#set $upstream animals-api:8080;\n        proxy_set_header
    \  X-Real-IP            $remote_addr;\n        proxy_set_header   X-Forwarded-For
    \     $proxy_add_x_forwarded_for;\n        proxy_set_header   X-Forwarded-Proto
    \   $scheme;\n        #proxy_set_header Host $http_host;\n\n\tproxy_pass    {{ .Values.tenantApi }};\n}\n\nlocation /register/ {\n        proxy_set_header
    \  X-Real-IP            $remote_addr;\n        proxy_set_header   X-Forwarded-For
    \     $proxy_add_x_forwarded_for;\n        proxy_set_header   X-Forwarded-Proto
    \   $scheme;\n        #proxy_set_header Host $http_host;\n\n\tproxy_pass {{ .Values.registerationService }};\n}\n"
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}
