apiVersion: v1
data:
{{- range .Values.apis }}
  pets-portal.conf: "location /animals/ {\n\tset $upstream {{ .host }}:{{ .port }};\n        proxy_set_header
    \  X-Real-IP            $remote_addr;\n        proxy_set_header   X-Forwarded-For
    \     $proxy_add_x_forwarded_for;\n        proxy_set_header   X-Forwarded-Proto
    \   $scheme;\n        proxy_set_header Host $http_host;\n\n\tproxy_pass http://$upstream/{{ .name }}/;\n}\n"
{{- end }}
kind: ConfigMap
metadata:
  name: pets-portal

