{{ if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pets-portal
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
  - host: {{ .Release.Namespace }}.{{ .Values.ingress.baseDomain }}
    http:
      paths:
      - backend:
          service:
            name: pets-portal
            port:
              number: 8080
        path: /
        pathType: Prefix
{{ end }}
