apiVersion: v1
data:
  pets-portal.conf: "{{- range .Values.apis }}location /animals/ {\n\t#set $upstream {{ .host }}:{{ .port }};\n        proxy_set_header
    \  X-Real-IP            $remote_addr;\n        proxy_set_header   X-Forwarded-For
    \     $proxy_add_x_forwarded_for;\n        proxy_set_header   X-Forwarded-Proto
    \   $scheme;\n        proxy_set_header Host $http_host;\n\n\tproxy_pass http://{{ .host }}:{{ .port }}/{{ .name }}/;\n}\n\n{{ end }}location /vaccines/ {\n        proxy_set_header
    \  X-Real-IP            $remote_addr;\n        proxy_set_header   X-Forwarded-For
    \     $proxy_add_x_forwarded_for;\n        proxy_set_header   X-Forwarded-Proto
    \   $scheme;\n        #proxy_set_header Host $http_host;\n\n\tproxy_pass  {{ .Values.vaccinesService }};\n}\n"
kind: ConfigMap
metadata:
  name: pets-portal

