apiVersion: v1
data:
  database-name: Y29sb3JwYWQ=
  database-password: YWx5
  database-user: YWx5
kind: Secret
metadata:
  annotations:
    template.openshift.io/expose-database_name: '{.data[''database-name'']}'
    template.openshift.io/expose-password: '{.data[''database-password'']}'
    template.openshift.io/expose-username: '{.data[''database-user'']}'
  labels:
    template: postgresql-ephemeral-template
    template.openshift.io/template-instance-owner: 48a869bc-cb55-4181-83d4-a53b95ff37da
  name: colorpad-db
type: Opaque
