apiVersion: v1
kind: Service
metadata:
  labels:
    app: colorpad-db
    template: postgresql-ephemeral-template
  name: colorpad-db
spec:
  ports:
  - name: colorpad-db
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: colorpad-db
    deployment: colorpad-db
  sessionAffinity: None
  type: ClusterIP
