apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"Deployment","name":"{{ .Values.counter}}"}]'
  labels:
    app: {{ .Values.color }}
    color: {{ .Values.color }}
    app.kubernetes.io/component: {{ .Values.color }}
    app.kubernetes.io/instance: {{ .Values.color }}
    app.kubernetes.io/part-of: colorpad
    app.openshift.io/runtime: {{ .Values.runtime }}
  name: {{ .Values.color }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: {{ .Values.color }}
      deployment: {{ .Values.color }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.color }}
        deployment: {{ .Values.color }}
    spec:
      containers:
      - env:
        - name: COLOR
          value: {{ .Values.color }}
        - name: COUNTER_SERVICE
          value: {{ .Values.counter_url }} 
        image: quay.io/aibrahim/node-colors-server:{{ .Values.version }}
        imagePullPolicy: Always
        name: {{ .Values.color }}
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      serviceAccount: {{ .Values.color }}
