apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "alb"
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}
spec:
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: 8080
  selector:
    app: {{ .Release.Name }}
  sessionAffinity: None
  type: {{ .Values.service.type }}
