apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"Deployment","name":"counter-v1"}]'
  labels:
    app: green
    color: green
    app.kubernetes.io/component: green
    app.kubernetes.io/instance: green
    app.kubernetes.io/part-of: colorpad
    app.openshift.io/runtime: nodejs
  name: green
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: green
      deployment: green
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: green
        deployment: green
    spec:
      containers:
      - env:
        - name: COLOR
          value: green
        - name: COUNTER_SERVICE
          value: http://counter:8080
        image: quay.io/aibrahim/node-colors-server:latest
        imagePullPolicy: Always
        name: green
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      serviceAccount: green
