apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/connects-to: >-
      [{"apiVersion":"apps/v1","kind":"Deployment","name":"postgresql"}]
  labels:
    app: counter
    version: v1
    app.kubernetes.io/component: counter
    app.kubernetes.io/instance: counter
    app.kubernetes.io/part-of: colorpad
    app.openshift.io/runtime: quarkus
  name: counter-v1
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: counter
      version: v1
      deployment: counter
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: counter
        version: v1
        deployment: counter
    spec:
      containers:
      - env:
        image: quay.io/aibrahim/counter-service-db-jvm:latest
        imagePullPolicy: Always
        name: counter
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: deployments/config/application.properties
          name: quarkus-conf
          subPath: application.properties
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: counter-config
        name: quarkus-conf
        
