apiVersion: v1
kind: Service
metadata:
  labels:
    app: counter
  name: counter
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: https-secure
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app: counter
    deployment: counter
  sessionAffinity: None
  type: ClusterIP
