apiVersion: v1
kind: Service
metadata:
  labels:
    app: orange
  name: orange
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: https-secure
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app: orange
    deployment: orange
  sessionAffinity: None
  type: ClusterIP
