apiVersion: v1
kind: Service
metadata:
  labels:
    app: purple
  name: purple
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app: purple
    deployment: purple
  sessionAffinity: None
  type: ClusterIP
