apiVersion: v1
kind: Service
metadata:
  labels:
    app: red
  name: red
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app: red
    deployment: red
  sessionAffinity: None
  type: ClusterIP
