apiVersion: v1
kind: Service
metadata:
  labels:
    app: colorpad
  name: colorpad
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
    appProtocol: http
  - name: https-secure
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app: colorpad
    deployment: colorpad
  sessionAffinity: None
  type: ClusterIP
