apiVersion: v1
kind: Service
metadata:
  labels:
    app: blue
  name: blue
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app: blue
    deployment: blue
  sessionAffinity: None
  type: ClusterIP
