{{ range .Values.apis }}
apiVersion: apigatewayv2.services.k8s.aws/v1alpha1
kind: Integration
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: "{{ $.Release.Name }}-{{ .name }}-integration"
spec:
  apiRef:
    from:
      name: "{{ $.Release.Name }}-{{ .name }}-api"
  integrationType: HTTP_PROXY
  integrationURI: {{ .url }}/{proxy}
  integrationMethod: {{ $.Values.method }} 
  payloadFormatVersion: "1.0"
{{- end }}
