{{ range .Values.apis }}
apiVersion: apigatewayv2.services.k8s.aws/v1alpha1
kind: API
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: {{ $.Release.Name }}-{{ .name }}-api
spec:
  name: {{ $.Release.Name }}-{{ .name }}-api
  protocolType: HTTP
{{ end }}
