apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
  name: hathor-api-service-tls
spec:
  dnsNames:
  - hathor-api.{{ .Release.Namespace }}
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: selfsigned-cluster-issuer
  secretName: hathor-api-tls
  usages:
  - digital signature
  - key encipherment

