apiVersion: v1
data:
  application.properties: |
    COLOR={{ .Values.color }}
    com.aliction.quarkuscolorsserver.CounterService/mp-rest/url=http://counter:8080
    com.aliction.quarkuscolorsserver.CounterService/mp-rest/scope=javax.inject.Singleton

    quarkus.jaeger.service-name=purple
    quarkus.jaeger.sampler-type=const
    quarkus.jaeger.sampler-param=1
    quarkus.log.console.format=%d{HH:mm:ss} %-5p traceId=%X{traceId}, parentId=%X{parentId}, spanId=%X{spanId}, sampled=%X{sampled} [%c{2.}] (%t) %s%e%n
kind: ConfigMap
metadata:
  name: quarkus-server-{{ .Values.color }}-config-{{ .Values.version }}
