apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgresql
    template: postgresql-ephemeral-template
  name: postgresql
spec:
  ports:
  - name: postgresql
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgresql
    deployment: postgresql
  sessionAffinity: None
  type: ClusterIP
