apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"Deployment","name":"purple"}, {"apiVersion":"apps/v1","kind":"Deployment","name":"red"},{"apiVersion":"apps/v1","kind":"Deployment","name":"blue-v1"},{"apiVersion":"apps/v1","kind":"Deployment","name":"green"},{"apiVersion":"apps/v1","kind":"Deployment","name":"orange"}]'
  labels:
    app: {{ .Values.appName }}
    version: {{ .Values.version }}
    app.kubernetes.io/component: {{ .Values.appName }}
    app.kubernetes.io/instance: {{ .Values.appName }}
    app.kubernetes.io/part-of: {{ .Values.appName }}
    app.openshift.io/runtime: angularjs
  name: {{ .Values.appName }}-{{ .Values.version }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: {{ .Values.appName }}
      version: {{ .Values.version }}
      deployment: {{ .Values.appName }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
        version: {{ .Values.version }}
        deployment: {{ .Values.appName }}
    spec:
      containers:
      - image: quay.io/aibrahim/{{ .Values.appName }}:{{ .Values.version }}
        imagePullPolicy: Always
        name: {{ .Values.appName }}
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/app-root/etc/nginx.default.d/{{ .Values.appName }}.conf
          name: nginx-conf
          subPath: {{ .Values.appName }}.conf
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: colors-routes
        name: nginx-conf
        
