kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{.Values.appName }}
  labels:
    app: {{ .Values.appName }}
  annotations:
    openshift.io/host.generated: 'true'
spec:
  to:
    kind: Service
    name: {{ .Values.appName  }}
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None
