apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.appName }}
  name: {{ .Values.appName }}
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
    appProtocol: http
  - name: https-secure
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app: {{ .Values.appName }}
    deployment: {{ .Values.appName }}
  sessionAffinity: None
  type: ClusterIP
