apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: https-secure
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app: {{ .Chart.Name }}
    deployment: {{ .Chart.Name }}
  sessionAffinity: None
  type: ClusterIP
