apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"Deployment","name":"counter-v1"}]'
  labels:
    app: {{ .Values.color }}
    version: {{ .Values.version }}
    color: {{ .Values.color }}
    app.kubernetes.io/component: {{ .Values.color }}
    app.kubernetes.io/instance: {{ .Values.color }}
    app.kubernetes.io/part-of: colorpad
    app.openshift.io/runtime: {{ .Values.runtime }}
  name: {{ .Values.color }}-{{ .Values.version }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: {{ .Values.color }}
      version: {{ .Values.version }}
      deployment: {{ .Values.color }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.color }}
        version: {{ .Values.version }}
        deployment: {{ .Values.color }}
    spec:
      containers:
      - env:
        - name: COLOR
          value: {{ .Values.color }}
        - name: COUNTER_SERVICE
          value: http://localhost:8080
        image: quay.io/aibrahim/quarkus-colors-server-jvm:{{ .Values.version }}
        imagePullPolicy: Always
        name: {{ .Values.color }}
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: deployments/config/application.properties
          name: quarkus-conf
          subPath: application.properties
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      serviceAccount: {{ .Values.color }}
      volumes:
      - configMap:
          defaultMode: 420
          name: quarkus-server-{{ .Values.color }}-config-{{ .Values.version }}
        name: quarkus-conf
        
