apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.color }}
  name: {{ .Values.color }}
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app: {{ .Values.color }}
    deployment: {{ .Values.color }}
  sessionAffinity: None
  type: ClusterIP
