kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Values.appName }}
spec:
  rules:
    - host: {{ .Values.appName }}-{{ $.Release.Namespace }}.{{ $.Values.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.appName }}
                port:
                  number: 8080
