apiVersion: v1
data:
  application.properties: |
    # server.port = 8888

    quarkus.datasource.db-kind = postgresql
    quarkus.datasource.username={{ .Values.db.dbUser }}
    quarkus.datasource.password={{ .Values.db.dbPass }}
    quarkus.datasource.jdbc.url = jdbc:postgresql://postgresql:5432/{{ .Values.db.dbName }}

    spring.jpa.show-sql=true

    ## Hibernate Properties
    # The SQL dialect makes Hibernate generate better SQL for the chosen database
    spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

    # Hibernate ddl auto (create, create-drop, validate, update)
    spring.jpa.hibernate.ddl-auto = update

    management.endpoints.web.exposure.include=health,info,prometheus

    quarkus.devservices.enabled=false
    {{- if .Values.service.ssl }}
    quarkus.http.ssl-port=8443
    quarkus.http.insecure-requests=redirect
    quarkus.http.ssl.certificate.files=/var/run/secrets/kubernetes.io/ssl/tls.crt
    quarkus.http.ssl.certificate.key-files=/var/run/secrets/kubernetes.io/ssl/tls.key
    {{- end }}

    quarkus.http.cors=true
    quarkus.http.cors.origins=*
    quarkus.http.cors.headers=accept, authorization,content-type
    quarkus.http.cors.methods=GET,POST,OPTIONS

    quarkus.banner.enabled=true

    mp.jwt.verify.issuer=https://cognito-idp.us-west-2.amazonaws.com/us-west-2_h8atoRNOJ
    quarkus.native.resources.includes=jwks.json
    smallrye.jwt.verify.key.location=jwks.json
    smallrye.jwt.verify.key.algorithm=RS256
    smallrye.jwt.path.groups=cognito:groups
    smallrye.jwt.claims.groups=none
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
